plugins:
  - rubocop-disable_syntax
  - rubocop-packaging
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 100
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/**/*"
Lint/ItWithoutArgumentsInBlock:
  Enabled: false
Lint/MissingSuper:
  Enabled: false

Metrics:
  Enabled: false

Style/DisableSyntax:
  DisableSyntax:
    - unless
    - and_or_not
    - numbered_parameters

Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NegatedIf:
  Enabled: false
